name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install System Deps
      run: |
        sudo apt install build-essential libpython3-dev libdbus-1-dev python3-gi python3-dev python3-gst-1.0 python-gi-dev
        sudo apt install libglib2.0-dev libglib2.0-dev-bin  libunwind-dev libtool m4 autoconf automake libgirepository1.0-dev libcairo2-dev
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
